version: '3.4'

services:
  dashboard:
    container_name: dashboard-happmobi
    image: happmobi-vehicle-reservation
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4200:80
